$primary = rgb(3584e4)
$surface = rgb(fafafa)
$secondary = rgb(2e3436)
$error = rgb(e01b24)
$tertiary = rgb(2ec27e)
$surface_lowest = rgb(fbfbfb)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
