background              #C6CDD2
foreground              #1E2931
cursor                  #3f8d6c
selection_foreground    #C6CDD2
selection_background    #223441
color0                  #C6CDD2
color8                  #5998c0
color1                  #BF616A
color9                  #CA727B
color2                  #206b00
color10                 #A3BE8C
color3                  #f37329
color11                 #f37329
color4                  #507b95
color12                 #5998c0
color5                  #B48EAD
color13                 #BF8FA1
color6                  #4CA1B3
color14                 #88C0D0
color7                  #1E2931
color15                 #07273b