"terminal.ansiBlack": "#182a35",
"terminal.ansiRed": "#c08872",
"terminal.ansiGreen": "#72c09f",
"terminal.ansiYellow": "#c8a984",
"terminal.ansiBlue": "#6196b8",
"terminal.ansiMagenta": "#c28097",
"terminal.ansiCyan": "#72b7c0",
"terminal.ansiWhite": "#c5cdd3",
"terminal.ansiBrightBlack": "#425866",

"terminal.ansiBrightRed": "#ca8468",
"terminal.ansiBrightGreen": "#84c8ab",
"terminal.ansiBrightYellow": "#d1aa7b",
"terminal.ansiBrightBlue": "#68a4ca",
"terminal.ansiBrightMagenta": "#c88da2",
"terminal.ansiBrightCyan": "#84c0c8",
"terminal.ansiBrightWhite": "#c5d1d3",

"terminal.background": "#0e1920",
"terminal.foreground": "#c5cdd3",
"terminalCursor.background": "#0e1920",
"terminalCursor.foreground": "#c5cdd3",
"editor.background": "#1b2932",
"editor.foreground": "#c5cdd3",