;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
#background = #1E2931aa
background = #182a35
background-alt = #1b2932
#foreground = #C6CDD2
foreground = #C6CDD2
primary = #C6CDD2
#primary = #F0C674
secondary = #8ABEB7
alert = #A54242
#disabled = #707880
disabled = #C6CDD2

[bar/top]
width = 100%
height = 20pt
radius = 0
monitor = ${env:MONITOR:}

background = ${colors.background}
foreground = ${colors.foreground}

padding-left = 1
padding-right = 1
module-margin = 1

font-0 = Iosevka NF:size=11;2
font-1 = "Font Awesome 6 Free:style=Solid;2"
font-2 = "Weather Icons:size=12;1"

modules-left = logo menu i3 xwindow
#modules-right = filesystem pulseaudio xkeyboard memory cpu wlan eth date active-network  xworkspaces menu-apps
modules-right =  pomo weather usb updates mail mail-work bluetooth clip xkeyboard pulseaudio battery date
#modules-center =  

cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true


[bar/bottom]
width = 100%
height = 20pt
#offset-y = -20  
radius = 0
monitor = ${env:MONITOR:}
bottom = true

background = ${colors.background}
foreground = ${colors.foreground}

padding-left = 1
padding-right = 1
module-margin = 1

font-0 = Iosevka NF:size=11;2
font-1 = "Font Awesome 6 Free:style=Solid;2"

modules-left = wireguard wlan eth publicip docker smb
modules-right = cpu temperature fs-home-icon fs-home-bar fs-home-text memory-icon memory-bar memory-text services
#modules-center = date 

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true


[module/xwindow]
type = internal/xwindow
#label = %title:0:60:...%
label = %title:0:150:...%
label-empty =   Desktop

[fs-base]
type = internal/fs
interval = 25
mount-0 = /
#label-mounted = %{F#F0C674}%mountpoint%%{F-} %percentage_used%%


[module/fs-home-icon]
inherit = fs-base
format-mounted = <label-mounted>
label-mounted = 󰋊  %fsname%

[module/fs-home-bar]
inherit = fs-base
format-mounted = <bar-free>
bar-free-width = 8
bar-free-empty = ░
bar-free-fill =  ▓
bar-free-indicator = ▓
bar-free-fill-foreground = #3d818f
bar-free-indicator-foreground = #3d818f


[module/fs-home-text]
inherit = fs-base
#label-mounted = %{F#F0C674}%mountpoint%%{F-} %percentage_used%%
format-mounted = <label-mounted>
label-mounted = %free% %{F#3d818f} / %total%%{F-}

#label-unmounted = %mountpoint% not mounted
#label-unmounted-foreground = ${colors.disabled}

[module/pulseaudio]
type = internal/pulseaudio

#format-volume-prefix = "  "
format-volume-prefix-foreground = ${colors.primary}
format-volume = <ramp-volume> <label-volume>

label-volume = %percentage%%

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 

label-muted = 󰝟 muted
label-muted-foreground = ${colors.disabled}
click-right = kitty -e pulsemixer

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock
blacklist-1 = scroll lock
format = <label-layout>
format-spacing = 4
layout-icon-0 = us;  US
layout-icon-1 = ru;  RU
label-layout = %icon%


[memory-base]
type = internal/memory
interval = 2
#label =   %used% %percentage_used:2%%
click-left = kitty --hold btop

[module/memory-icon]
inherit = memory-base
label =   %percentage_used:2%%
click-left = kitty --hold btop


[module/memory-bar]
inherit = memory-base
format = <bar-used>
bar-used-width = 8
bar-used-empty = ░
bar-used-fill = ▓
bar-used-indicator = ▓
bar-used-fill-foreground = #3d818f
bar-used-indicator-foreground = #3d818f
click-left = kitty --hold btop


[module/memory-text]
inherit = memory-base
label = %used% %{F#3d818f} / %total%%{F-}
click-left = kitty --hold btop

[module/cpu]
type = internal/cpu
interval = 2
#format-prefix = "CPU "
format-prefix-foreground = ${colors.primary}
label =   %percentage%%

#[module/active-network]
#type = custom/script
#exec = ~/.config/polybar/scripts/active_interface.sh
#tail = true
#interval = 5
#format = <label>
#label = %output%
#click-left = kitty -e nmtui

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
click-left = kitty -e nmtui
label-disconnected = 
#label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

[module/wlan]
inherit = network-base
interface-type = wireless
#label-connected = %{F#F0C674}%ifname%%{F-}  %local_ip%
label-connected = 󰈀  %ifname%: %local_ip% %{F#3d818f}  %essid%%{F-}

[module/eth]
inherit = network-base
interface-type = wired
#label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%
label-connected = 󰈀  %ifname%: %local_ip%

[module/date]
type = internal/date
interval = 1

date-alt = %H:%M
date =   %a %d %b %H:%M

label = %date%
#label-foreground = ${colors.primary}
label-foreground = ${colors.foreground}

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini

[module/bluetooth]
type = custom/script
exec = ~/.config/polybar/scripts/bluetooth-module.sh
interval = 5

; Обработчики кликов
click-left = kitty -e bluetoothctl
click-middle = ~/.config/polybar/scripts/toggle-bluetooth.sh
click-right = kitty -e cat ~/.config/polybar/cheatsheets/bluetoothctl.md
; Стилизация (настройте под свою тему)
format = <label>
label = %output%
#format-foreground = #88c0d0  ; цвет текста
#format-background = #2e3440  ; фон
#format-padding = 4

[module/clip]
type = custom/text
click-left = ~/.config/i3/scripts/clipboard.sh
format = <label>
label = 

[module/menu]
type = custom/text
click-left = ~/.config/rofi/launchers/type-1/launcher.sh
format = <label>
label =Think and keep it simple

[module/logo]
type = custom/text
click-left = ~/.config/rofi/powermenu/type-1/powermenu.sh
format = <label>
label = 

[module/battery]
type = internal/battery
full-at = 99
low-at = 20
; Use the following command to list batteries and adapters:
; $ ls -1 /sys/class/power_supply/
battery = BAT0
adapter = AC
poll-interval = 5
time-format = %H:%M

format-charging = <animation-charging> <label-charging>
format-discharging = <ramp-capacity>  <label-discharging>
format-low = <label-low> <animation-low>

label-charging = %percentage%%
label-discharging = %percentage%%
label-full = 
label-low = %{F#FF2c2c}  %percentage%%%{F-}  

; Only applies if <ramp-capacity> is used
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 

bar-capacity-width = 10

animation-charging-0 =  󱐋
animation-charging-1 =  󱐋
animation-charging-2 =  󱐋
animation-charging-3 =  󱐋
animation-charging-4 =  󱐋
animation-charging-framerate = 750

animation-discharging-0 = 
animation-discharging-1 = 
animation-discharging-2 = 
animation-discharging-3 = 
animation-discharging-4 = 
animation-discharging-framerate = 500

animation-low-0 = !
animation-low-1 = 
animation-low-framerate = 500

[module/i3]
type = internal/i3
pin-workspaces = true
show-urgent = true

; This will split the workspace name on ':'
; Default: false
strip-wsnumbers = true
index-sort = true
enable-click = true
enable-scroll = false
wrapping-scroll = false
reverse-scroll = false

fuzzy-match = true

; ws-icon-[0-9]+ = <label>;<icon>
; NOTE: The <label> needs to match the name of the i3 workspace
; Neither <label> nor <icon> can contain a semicolon (;)
ws-icon-0 = 1;♚
ws-icon-1 = 2;♛
ws-icon-2 = 3;♜
ws-icon-3 = 4;♝
ws-icon-4 = 5;♞
ws-icon-default = ♟
; NOTE: You cannot skip icons, e.g. to get a ws-icon-6
; you must also define a ws-icon-5.
; NOTE: Icon will be available as the %icon% token inside label-*
;https://ya.ru
; Available tags:
;   <label-state> (default) - gets replaced with <label-(focused|unfocused|visible|urgent)>
;   <label-mode> (default)
format = <label-state> <label-mode>

; Available tokens:
;   %mode%
; Default: %mode%
label-mode = %mode%
label-mode-padding = 1
label-mode-background = #e60053

; Available tokens:
;   %name%
;   %icon%
;   %index%
;   %output%
; Default: %icon% %name%
label-focused = %index%
label-focused-foreground = ${colors.foreground}
label-focused-background = #243742
label-focused-underline = ${colors.foreground}
label-focused-padding = 1

; Available tokens:
;   %name%
;   %icon%
;   %index%
;   %output%
; Default: %icon% %name%
label-unfocused = %index%
label-unfocused-padding = 1

; Available tokens:
;   %name%
;   %icon%
;   %index%
;   %output%
; Default: %icon% %name%
label-visible = %index%
label-visible-underline = #555555
label-visible-padding = 1

; Available tokens:
;   %name%
;   %icon%
;   %index%
;   %output%
; Default: %icon% %name%
label-urgent = %index%
label-urgent-foreground = ${colors.foreground}
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

; Separator in between workspaces
label-separator = 
label-separator-padding = 1
label-separator-foreground = #ffb52a

[module/menu-apps]
type = custom/menu

; If true, <label-toggle> will be to the left of the menu items (default).
; If false, it will be on the right of all the items.
expand-right = true

; "menu-LEVEL-N" has the same properties as "label-NAME" with
; the additional "exec" property
;
; Commands will be executed using "/bin/sh -c $COMMAND"

menu-0-0 = Browsers
menu-0-0-exec = #menu-apps.open.1
menu-0-1 = Multimedia
menu-0-1-exec = #menu-apps.open.2

menu-1-0 = Firefox
menu-1-0-exec = firefox
menu-1-1 = Chromium
menu-1-1-exec = chromium

menu-2-0 = Gimp
menu-2-0-exec = gimp
menu-2-1 = Scrot
menu-2-1-exec = scrot
; Available tags:
;   <label-toggle> (default) - gets replaced with <label-(open|close)>
;   <menu> (default)
; If expand-right is true, the default will be "<label-toggle><menu>" and the
; other way around otherwise.
; Note that if you use <label-toggle> you must also include
; the definition for <label-open>
; format = <label-toggle><menu>

label-open = Apps
label-close = x

; Optional item separator
; Default: none
label-separator = |

[module/temperature]
type = internal/temperature

interval = 1
thermal-zone = 0

zone-type = x86_pkg_temp
hwmon-path = /sys/devices/platform/coretemp.0/hwmon/hwmon2/temp1_input

base-temperature = 20
warn-temperature = 75

units = true
format = <ramp> <label>
format-warn = <ramp> <label-warn>

label = %temperature-c%
label-warn = %temperature-c%
label-warn-foreground = ${colors.alert}

ramp-0 = 
ramp-1 = 
ramp-2 = 
#ramp-foreground = #55

[module/weather]
type = custom/script
exec = echo "$(curl -4 -sf 'https://wttr.in/?format=1')"
#echo "# $(curl -4 -sf ifconfig.co)"
interval = 600
#label-font = 3

[module/publicip]
type = custom/script
exec = echo "󰖟  $(curl -4 -sf ifconfig.co)"
click-left = curl -4 -sf ifconfig.co | xclip -selection clipboard
interval = 60

[module/usb]
type = custom/script
interval = 10
exec = ~/.config/polybar/scripts/mount.sh
tail = true
click-left = kitty --hold flatpak run io.github.sxyazi.yazi /media/link
click-right = udisksctl unmount -b /dev/sdb1

[module/smb]
type = custom/script
interval = 10
exec = ~/.config/polybar/scripts/smb.sh
click-left = ~/.config/rofi/launchers/type-1/smb.sh
click-right = kitty --hold flatpak run io.github.sxyazi.yazi /mnt
click-middle = ~/.config/polybar/scripts/disconnect_smb.sh

[module/wireguard]
type = custom/script
interval = 10
exec = ~/.config/polybar/scripts/check_wireguard.sh
click-left = ~/.config/rofi/launchers/type-1/wireguard.sh
click-right = ~/.config/polybar/scripts/disconnect_wireguard.sh

[module/updates]
type = custom/script
interval = 100
exec = ~/.config/polybar/scripts/updates.sh
click-left = kitty --hold sudo apt update

[module/mail]
type = custom/script
exec = ~/.config/polybar/scripts/mail.py
interval = 30
label =  %output%
click-left = exec evolution &

[module/mail-work]
type = custom/script
exec = ~/.config/polybar/scripts/mail-work.py
interval = 30
label = 󰊫 %output%
click-left = exec evolution &

[module/docker]
type = custom/script
exec = docker ps -q | wc -l
interval = 5
label =  %output%
click-left = kitty --hold lazydocker

[module/services]
type = custom/script
exec = systemctl --type=service --state=running list-units --no-pager | grep running | wc -l
interval = 10
label =  %output%
click-left = ~/.config/polybar/scripts/services.sh

[module/pomo]
type = custom/script
exec = ~/.config/polybar/scripts/pomodoro_timer.py
click-left = "~/.config/polybar/scripts/pomodoro_timer.py toggle"
click-right = "~/.config/polybar/scripts/pomodoro_timer.py skip"
click-middle = "~/.config/polybar/scripts/pomodoro_timer.py reset"
interval = 1
label = %output%